import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import ScrollToTop from "react-scroll-to-top";
import Announcements from '../components/UpcomingEvents';
import MainGrid from '../components/MainGrid';

export default function Home() {
  const mainStyle = {
    position: 'absolute',
    overflowX: 'clip',
    height: 'fit-content',
    top: '0',
    left: '0',
    width: '100%',
    margin: '0 auto'
  }

  const scrollStyle = {
    height: '65px',
    width: '65px',
    borderRadius: '50%',
  }

  return (
    <div style={mainStyle}>
      <Head>
        <title>NITH CSE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <ScrollToTop smooth='true' width={30} height={30} style={scrollStyle} />
      <Header />
      <MainGrid />
      <Announcements />
      <Footer />
    </div>
  )
}
